elixir/patient/urls.py
from django.conf.urls import url

from .views import PatientListView, PatientCreateView
from record import views
from record.views import RecordUpdateView, RecordSearchView, RecordDetailView, CreateNoteView, NoteSearchView, NoteDetailView

urlpatterns = [
	url(r'^new_patient/$', PatientCreateView.as_view(), name='new_patient'),
	url(r'^update/(?P<pk>[0-9]+)/$', RecordUpdateView.as_view(), name='update_record'),
	url(r'^note/(?P<pk>[0-9]+)/$', CreateNoteView.as_view(), name='add_note'),
	url(r'^detail/(?P<pk>[0-9]+)/$', RecordDetailView.as_view(), name='detail_record'),
	#url(r'^view/$', 'record.views.record_list', name='view_record'),
	url(r'^view/$', RecordSearchView.as_view(), name='view_record'),
	url(r'^view_note/(?P<pk>[0-9]+)/$', NoteSearchView.as_view(), name='view_note'),
	url(r'^detail_note/(?P<pk>[0-9]+)/$', NoteDetailView.as_view(), name='detail_note'),
	#url(r'^list/$', PatientListView.as_view(), name='patient_list'),
]

elixir/record/urls.py
from django.conf.urls import url

from .views import RecordCreateView

urlpatterns = [
]

elixir/users/urls.py
from django.conf.urls import patterns, include, url

from users import views
from users.views import MenuAppView

urlpatterns = [
	url(r'^menu/$', MenuAppView.as_view(), name='menu'),
	url(r'^app_search/$', 'users.views.app_search', name='app_search'),
	url(r'^app_menu/$', 'users.views.app_menu', name='app_menu'),
	url(r'^record_search/$', 'users.views.record_search', name='record_search'),
	url(r'^record_menu/$', 'users.views.record_menu', name='record_menu'),
	url(r'^hipaa/$', 'users.views.hipaa', name='hipaa'),
	url(r'^accounts/', include('registration.backends.default.urls')),

   	
]

elixir/appointment/models.py
from __future__ import unicode_literals

from elixir.settings import celery_app
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from timezone_field import TimeZoneField

from patient.models import Record


import arrow


@python_2_unicode_compatible
class Appointment(models.Model):
    record = models.ForeignKey(Record)
    phone_number = models.CharField(max_length=15)
    time = models.DateTimeField()
    time_zone = TimeZoneField(default='America/Puerto_Rico')
    treatment = models.CharField(max_length = 255, null = True)

    # Additional fields not visible to users
    task_id = models.CharField(max_length=50, blank=True, editable=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Appointment #{0} - {1}'.format(self.pk, self.name)

    def get_absolute_url(self):
        return reverse('view_appointment', args=[str(self.id)])

    def clean(self):
        """Checks that appointments are not scheduled in the past"""

        appointment_time = arrow.get(self.time, self.time_zone.zone)

        if appointment_time < arrow.utcnow():
            raise ValidationError('You cannot schedule an appointment for the past. Please check your time and time_zone')

    def schedule_reminder(self):
        """Schedules a Celery task to send a reminder about this appointment"""

        # Calculate the correct time to send this reminder
        appointment_time = arrow.get(self.time, self.time_zone.zone)
        reminder_time = appointment_time.replace(minutes=-settings.REMINDER_TIME)

        # Schedule the Celery task
        from .tasks import send_sms_reminder
        result = send_sms_reminder.apply_async((self.pk,), eta=reminder_time)

        return result.id

    def save(self, *args, **kwargs):
        """Custom save method which also schedules a reminder"""

        # Check if we have scheduled a reminder for this appointment before
        if self.task_id:
            # Revoke that task in case its time has changed
            celery_app.control.revoke(self.task_id)

        # Save our appointment, which populates self.pk,
        # which is used in schedule_reminder
        super(Appointment, self).save(*args, **kwargs)

        # Schedule a new reminder task for this appointment
        self.task_id = self.schedule_reminder()

        # Save our appointment again, with the new task_id
        super(Appointment, self).save(*args, **kwargs)

elixir/patient/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from doctor.models import Doctor
from django.db.models.signals import post_save
from django.contrib.auth.models import User
import datetime

from django.db import models


class Patient(models.Model):

	SEX = (
			('M','Masculino'),
			('F','Femenino'),
		)

	name = models.CharField(max_length = 30, default = '')
	mid_name = models.CharField(max_length = 1, blank=True, null=True)
	first_last_name = models.CharField(max_length = 30, default = '')
	second_last_name = models.CharField(max_length = 30, default = '')
	birthdate = models.DateField()
	sex = models.CharField(max_length = 1, choices = SEX)
	address1 = models.CharField(max_length = 100)
	address2 = models.CharField(max_length = 100, blank=True, null=True)
	city = models.CharField(max_length = 50)
	state = models.CharField(max_length = 2)
	zipcode = models.CharField(max_length = 10, default='')
	phone = models.CharField(max_length = 20, blank=True, null=True)
	doctor = models.ForeignKey(Doctor)
	

	def get_absolute_url(self):
		return reverse('update_record', args=[str(self.id)])

	def __str__(self):
		return self.name + ' ' + self.first_last_name

def record_save(sender, instance, created, *args, **kwargs):
	patient = instance
	new_rec = Record()
	new_rec.patient = patient
	new_rec.save()

post_save.connect(record_save, sender = Patient)

class Record(models.Model):
	patient = models.OneToOneField(Patient)
	medical_plan_name = models.CharField(max_length = 30, blank=True, null=True)
	medical_plan_number = models.CharField(max_length = 30, blank=True, null=True)
	height = models.FloatField(blank=True, null=True)
	weight = models.FloatField(blank=True, null=True)
	condition_1 = models.CharField(max_length = 30, blank=True, null=True)
	condition_2 = models.CharField(max_length = 30, blank=True, null=True)
	condition_3 = models.CharField(max_length = 30, blank=True, null=True)
	more_info = models.CharField(max_length = 255, blank=True, null=True)
	created_By = models.ForeignKey(User, related_name = 'user', blank=True, null=True)
	created_DT = models.DateField(default = datetime.date.today(), blank=True, null=True)
	modified_By = models.ForeignKey(User, blank=True, null=True)
	modified_DT = models.DateField(blank=True, null=True)

	def get_absolute_url(self):
		return reverse('update_record', args=[str(self.id)])
		
	def __str__(self):
		return self.patient.name + ' ' + self.patient.first_last_name
	
class Note(models.Model):

	RECEIVEDPLACE = (
			('Cuarto','Cuarto'),
			('Sala','Sala'),
			('Comedor','Comedor'),
			('Area de Juegos','Area de Juegos'),
		)
	RECEIVEDSTATE = (
			('Dormido','Dormido'), 
			('Despierto','Despierto'),
		)
	SERVICEFOOD = (
			('Desayuno','Desayuno'),
			('Almuerzo','Almuerzo'),
			('Cena','Cena'),
		)
	RANGE = (
			('0','0'),
			('1-2','1-2'),
			('3-4','3-4'),
			('5-6','5-6'),
		)
	record = models.ForeignKey(Record, blank=True, null=True)
	created_by = models.CharField(max_length = 30)
	created_dt = models.DateField(auto_now_add=True)
	created_tm = models.TimeField(auto_now_add=True)
	received_Place = models.CharField(max_length = 30, choices = RECEIVEDPLACE, blank=True, null=True)
	received_State = models.CharField(max_length = 30, choices = RECEIVEDSTATE, blank=True, null=True)
	service_Food = models.CharField(max_length = 30, choices = SERVICEFOOD, blank=True, null=True)
	returned_Type = models.CharField(max_length = 30, choices = RECEIVEDPLACE, blank=True, null=True)
	diaper = models.CharField(max_length = 10, choices = RANGE, blank=True, null=True)
	evacuations = models.CharField(max_length = 10, choices = RANGE, blank=True, null=True)
	milk = models.CharField(max_length = 10, choices = RANGE, blank=True, null=True)
	snack = models.CharField(max_length = 10, choices = RANGE, blank=True, null=True)
	hygiene = models.CharField(max_length = 10, choices = RANGE, blank=True, null=True)
	comments = models.TextField(blank=True, null=True)

	def form_valid(self, form):
		obj = form.save(commit=False)
		obj.created_by = self.request.user
		obj.save()
		return http.HttpResponseRedirect(self.get_success_url())

	def __str__(self):
		return str(self.created_dt )

elixir/record/models.py
from __future__ import unicode_literals

from django.db import models

elixir/patient/views.py
from django.shortcuts import render
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from django.views.generic import DetailView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Patient


class PatientListView(ListView):
    model = Patient

class PatientDetailView(DetailView):
    model = Patient


class PatientCreateView(SuccessMessageMixin, CreateView):
    model = Patient
    context_object_name = 'patient'
    template_name = 'patient/patient_form.html'
    fields = ['name', 'mid_name', 'first_last_name', 'second_last_name', 'birthdate','sex','address1','address2','city','state','zipcode','phone', 'doctor']
    success_message = 'Patient successfully created.'

class PatientUpdateView(SuccessMessageMixin, UpdateView):
    model = Patient
    fields = ['name', 'mid_name', 'first_last_name', 'second_last_name', 'birthdate','sex','address1','address2','city','state','zipcode','phone']
    success_message = 'The new Patient is updated.'


class PatientDeleteView(DeleteView):
    model = Patient
    success_url = reverse_lazy('dash')

elixir/record/views.py
from django.http import *
from django.core.exceptions import ImproperlyConfigured
from django.shortcuts import render
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.views.generic import ListView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView

from django_filters import FilterSet, CharFilter

from django.shortcuts import get_object_or_404

from patient.models import Record, Patient, Note

class RecordFilter(FilterSet):
  name = CharFilter(name='name', lookup_type= 'icontains')
  lastname = CharFilter(name='first_last_name', lookup_type= 'icontains')
  class Meta:
    model = Patient
    fields = [
      'name',
      'lastname',
    ]

def record_list(request):
  qs = Patient.objects.all()
  ordering = request.GET.get("ordering")
  if ordering:
    qs = Patient.objects.all().order_by(ordering)
  f =  RecordFilter(request.GET, queryset = qs)
  return render(request, 'record/record_view.html', { "object_list": f })


class NoteFilter(FilterSet):
  record = CharFilter(name='record', lookup_type= 'icontains')
  class Meta:
    model = Patient
    fields = [
      'record',
    ]

def note_list(request):
  qs = Note.objects.all()
  ordering = request.GET.get("ordering")
  if ordering:
    qs = Note.objects.all().order_by(ordering)
  f =  NoteFilter(request.GET, queryset = qs)
  return render(request, 'record/note_view.html', { "object_list": f })



class FilterMixin(object):
  filter_class = None
  search_ordering_param = "ordering"

  def get_queryset (self, *args, **kwargs):
    try:
      qs = super(FilterMixin, self).get_queryset(*args, **kwargs)
      return qs
    except:
      raise ImproperlyConfigured("You must have a queryset in order to use FilterMixin")

  def get_context_data(self, *args, **kwargs):
    context = super(FilterMixin, self).get_context_data(*args, **kwargs)
    qs = self.get_queryset()
    ordering = self.request.GET.get(self.search_ordering_param)
    if ordering:
      qs = qs.order_by(ordering)
    filter_class= self.filter_class
    if filter_class:
      f = filter_class(self.request.GET, queryset=qs)
      context["object_list"] = f
    return context


class RecordSearchView(FilterMixin, ListView):
    template_name = 'record/record_view.html'
    model = Patient
    queryset = Patient.objects.all()
    filter_class = RecordFilter

    
    def get_context_data(self, *args, **kwargs):
      context = super(RecordSearchView, self).get_context_data(*args, **kwargs)
      context["query"] = self.request.GET.get("q")
      return context
    
    def get_queryset(self, *args, **kwargs):
      qs = super(RecordSearchView, self).get_queryset(*args, **kwargs)
      query = self.request.GET.get("q")
      if query:
        qs = self.model.objects.filter(
          Q(name__icontains = query)
          )

      return qs

class RecordDetailView(DetailView):
    model = Record
    template_name = 'record/record_detail.html'
    context_object_name = 'record'


class RecordCreateView(SuccessMessageMixin, CreateView):
    model = Record
    fields = ['medical_plan_name', 'medical_plan_number', 'height', 'weight', 'condition_1','condition_2','condition_3','more_info','created_By','created_DT']
    success_message = 'Record successfully created.'
    success_url = reverse_lazy('menu')


class RecordUpdateView(SuccessMessageMixin, UpdateView):
    model = Record
    context_object_name = 'record'
    template_name = 'record/record_update.html'
    fields = ['medical_plan_name', 'medical_plan_number', 'height', 'weight', 'condition_1','condition_2','condition_3','more_info','created_By','created_DT']
    success_message = 'The record is updated.'
    success_url = reverse_lazy('menu')


class RecordDeleteView(DeleteView):
    model = Record
    success_url = reverse_lazy('menu')


class CreateNoteView(CreateView):
    model = Note
    template_name = 'record/add_note.html'
    fields = ['received_Place','received_State','service_Food','returned_Type','diaper','evacuations','milk','snack', 'hygiene', 'comments']
    success_message = 'Note successfully created.'
    success_url = reverse_lazy('menu')

    def form_valid(self, form):
      form.instance.record = Record.objects.get(id = self.kwargs["pk"])
      form.save()
      return super(CreateNoteView, self).form_valid(form)


class NoteSearchView(FilterMixin, ListView):
    template_name = 'record/note_view.html'
    model = Note
    filter_class = NoteFilter

    
    def get_context_data(self, *args, **kwargs):
      context = super(NoteSearchView, self).get_context_data(*args, **kwargs)
      context["query"] = self.request.GET.get("q")
      context["record"] = self.kwargs["pk"]
      return context
    
    def get_queryset(self, *args, **kwargs):
      qs = super(NoteSearchView, self).get_queryset(*args, **kwargs)
      # query = self.request.GET.get("q")
      # if query:
      #   qs = self.model.objects.filter(
      #     Q(name__icontains = query)
      #     )
      record = Record.objects.get(id = self.kwargs["pk"])
      qs = Note.objects.filter(record = record)

      return qs

class NoteDetailView(DetailView):
    model = Note
    template_name = 'record/note_detail.html'
    context_object_name = 'note'
    

elixir/templates/patient/patient_form.html
{% extends 'dashboard.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% load crispy_forms_tags %}


 {% block navbar-content %}
    <form class="navbar-form navbar-left" role="search" id='searchform' action="{% url 'view_record' %}">
        <div class="form-group">
          <input type="text" name="name" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-success">Search</button>
      </form>

    <script type="text/javascript">
      $(function(){
      $("name").keyup(function(event){
        if(event.which == 13){
          document.searchform.submit();
          }
      });

    </script>
      <li class="dropdown" >
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user }} <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li role="separator" class="divider"></li>
          <li class="dropdown-header"></li>
          <li><a href="{% url 'logout' %}?next={{request.path}}">Log out</a></li>
        </ul>
      </li>  
  {% endblock navbar-content %}

  {% block sidebar-content %}
    <br>
    <li class="active"><a href="{% url 'new_patient' %}">New Patient<span class="sr-only">(current)</span></a></li>
    <li><a href="{% url 'view_record'%}">Patients List</a></li>
    <li><a href="{% url 'new_appointment'%}">New Appointment</a></li>
    <li><a href="{% url 'list_appointments'%}">Appointment List</a></li>
  {% endblock sidebar-content %}
          
  {% block fluid-content %} 
  {% if user.is_authenticated %}
    <h1 class="page-header">Create a new Patient</h1>
    <div class="jumbotron">
      <div class="container">
        <form class="form-horizontal" method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <div class="form-group">
            <div class="col-sm-offset-8 col-sm-10">
              <a href="{% url 'menu' %}" class="btn btn-default">Cancel</a>
              <button type="submit" class="btn btn-primary">
                Create patient
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>

  {% else %}
    <center>
      <div style="width: 50% " class="jumbotron">
        <div class="container">
          <img src="{% static 'imgs/slogan.png' %}" class="img-responsive" id="name">
          <hr>
          <h2>Go to login.</h2>
          <br>
          <p>
            <a style="width: 40%" class="btn btn-success btn-lg" href="{% url 'login' %}" >login</a>
          </p>
        </div>
      </div>
    </center>  {% endif %}
  {% endblock fluid-content %}

  {% block page_js %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>

  <script type="text/javascript">
      $(function() {
          $('#id_birthdate').datetimepicker({
            format: 'MM/DD/YYYY',
            extraFormats: ['YYYY-MM-DD'],
            sideBySide: true
          });
      });
  </script>
  {% endblock %}

elixir/templates/patient/record_form.html
{% extends 'dashboard.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}

 {% block navbar-content %}
    <li><a href="#">Dashboard</a></li>
    <li><a href="#">Settings</a></li>
    <li><a href="#">Profile</a></li>
    {% if user.is_authenticated %}
      <li class="dropdown" >
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.first_name }}{{user.last_name}} <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li role="separator" class="divider"></li>
          <li class="dropdown-header"></li>
          <li><a href="{% url 'logout' %}">Log out</a></li>
        </ul>
      </li>
      {% else %}
      <li><a href="{% url 'login' %}">Login</a></li>
    {% endif %}
  {% endblock navbar-content %}
  
  {% block sidebar-content %}
    <li><a href="{% url 'dash' %}">Dashboard</a></li>
    <li class="active"><a href="{% url 'new_patient' %}">New Patient<span class="sr-only">(current)</span></a></li>
    <li><a href="{% url 'dash' %}">Use a Record</a></li>
    <li><a href="#">View a Record</a></li>
    <li><a href="#">Edit a Redord</a></li>
  {% endblock sidebar-content %}
          
  {% block fluid-content %} 
    <h1 class="page-header">Create a Record for: {{ Patient.name }}</h1>
    <div class="jumbotron">
      <div class="container">
        <form class="form-horizontal" method="post">
          {% csrf_token %}
          {{ form|as_bootstrap_horizontal }}
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <a href="#back" class="btn btn-default">Cancel</a>
              <button type="submit" class="btn btn-primary">
                Create patient
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>

  {% endblock fluid-content %}

  {% block page_js %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>

  <script type="text/javascript">
      $(function() {
          $('#id_time').datetimepicker({
            format: 'MM/DD/YYYY HH:mm',
            extraFormats: ['YYYY-MM-DD HH:mm:ss'],
            sideBySide: true
          });
      });
  </script>
  {% endblock %}